### PR TITLE
Fix "Portal notification of new user is missing user.username"

### PR DESCRIPTION
**Pull request by n2ygk**
fixes https://github.com/gravitee-io/issues/issues/2132
- replace user.username with user.displayName

### CODE REVIEW

**Comment by brasseld** [comment]
Hi @n2ygk 

Thanks a lot for the PR!

Can you please sign the CLA before going further: https://download.gravitee.io/cla.pdf and send it to contact (at) graviteesource.com

**Comment by n2ygk** [comment]
I have sent it to my General Counsel who is not in favor of these
agreements mostly due to the administrative burden. If she says it’s OK,
then I’ll sign it.

See also
https://ben.balter.com/2018/01/02/why-you-probably-shouldnt-add-a-cla-to-your-open-source-project/

where the GitHub inbound = outbound rule is cited.

We are still just looking at Gravitee APIM and are not committed to using
it just yet. Meanwhile I figured I’d contribute as I can.

**Comment by n2ygk** [comment]
It seems clause 5 of the
https://github.com/gravitee-io/gravitee-management-rest-api/blob/master/LICENSE.txt
should be sufficient.

**Comment by n2ygk** [comment]
Despite my whining, the CLA is in the mail.

**Pull request merged**
