### PR TITLE
Improve generation of swagger definition

### PR DESCRIPTION
**Pull request by Andy2003**
apply additional adjustments for gravitee-io/issues#4394 
resolves https://github.com/gravitee-io/issues/issues/4533

### CODE REVIEW

**Comment by aelamrani** [comment]
@Andy2003 

May I ask you to create a dedicated issue for this? That way, we will move it to the correct milestone and place it in review.

Thanks

**Comment by aelamrani** [comment]
Hi @Andy2003 

You have some conflicts to resolve here.

**Comment by Andy2003** [comment]
@aelamrani done

**Comment by aelamrani** [comment]
@Andy2003 Thanks for this contribution

**Pull request merged**
