### PR TITLE
Provide userLogoutEndpoint for frontend

### PR DESCRIPTION
**Pull request by kanischev**
if there is any in identity provider configuration

### CODE REVIEW

**Comment by brasseld** [comment]
Hi @kanischev 

Thanks a lot for the PR!

Can you please sign the CLA before going further: https://download.gravitee.io/cla.pdf and send it to contact (at) graviteesource.com

**Comment by brasseld** [comment]
Hi @kanischev 

Any news here ?

**Comment by kanischev** [comment]
Hi @brasseld 
Sorry for delay. Have been busy for a while. 
I'll try to sign and send docs today in the evening. Thanks.

**Comment by brasseld** [comment]
Hi @kanischev 

No worries, and thanks for your feedback.
We are near the 1.25.0 release and I would love to embed this fix into it.

Looking forward to validate your PR :)

**Comment by brasseld** [comment]
Thanks a lot @kanischev

**Pull request merged**
