### PR TITLE
Bugfix/missing params in swagger definition 3.1

### PR DESCRIPTION
**Pull request by Andy2003**
merge 3.0.10 into 3.1.x and apply additional adjustments for https://github.com/gravitee-io/issues/issues/4394

### CODE REVIEW

**Comment by aelamrani** [comment]
Hi @Andy2003 

Seems you have some conflicts here :)

**Comment by Andy2003** [comment]
@aelamrani you need to build https://github.com/gravitee-io/gravitee-repository/pull/177

**Comment by aelamrani** [comment]
@Andy2003 I mean, we cannot merge your pull request. Can you rebase your branch with the 3.1?

**Comment by Andy2003** [comment]
This is b/c of the merge of tag 3.0.10 into 3.1.x. when I rebase my branch you will double history

**Comment by aelamrani** [comment]
@Andy2003 

First of all, 3.1.x is not under support anymore.

So I would suggest to start your changes from the 3.2.x branch and then ask for a pull request on the 3.2.x. That way, you will not have this commits in double...

**Comment by Andy2003** [comment]
@aelamrani and who is responsible for merging the 3.0.x / 3.1.x commits which are currently not part of the 3.2.x branch into 3.2.x? I want to do the final adjustments for 501ad077a77a1c0136ea7d212081ae1a002a0d25 in `3.2.x` as pointed out in (https://github.com/gravitee-io/gravitee-management-rest-api/pull/1196#issuecomment-704250287 and https://github.com/gravitee-io/issues/issues/4394#issuecomment-714509514)

**Comment by aelamrani** [comment]
We will manage it don't worry.

We are merging everything (bugfixes / enhancements) until the master branch.

**Comment by Andy2003** [comment]
@aelamrani I thought I can support here with this PR, but as it seems I have to wait until I can apply my adjustments regarding gravitee-io/issues#4394

**Pull request closed without merging**
