### PR TITLE
fix(management): the enums not case-insensitive when an api is imported

### PR DESCRIPTION
**Pull request by GGui**
Closes gravitee-io/issues#2995

### CODE REVIEW

**Comment by NicolasGeraud** [comment]
Hi @GGui can you please add some unit tests ?

**Comment by aelamrani** [comment]
@GGui Why not having the same behavior for all enums? And not only on Api.

**Comment by aelamrani** [comment]
It should be done quite easily as proposed here: https://stackoverflow.com/a/44217670

**Comment by GGui** [comment]
Ok thank you. I'm going to check. Sorry i didn't have time to work on it

**Comment by GGui** [comment]
Done ;-)

**Pull request merged**
