### PR TITLE
fix: using an empty string if the password is null to avoid Exception

### PR DESCRIPTION
**Pull request by Raphcal**
fix gravitee-io/issues#1435

### CODE REVIEW

**Comment by Raphcal** [comment]
Sorry for that. I fixed the line endings.
I will try to write the unit tests tomorrow.

**Comment by brasseld** [comment]
No problem, it's better like this ;)

So I'm waiting for UTs before merging this PR.

Thanks again!

**Comment by Raphcal** [comment]
Done, unit tests added.

**Comment by brasseld** [comment]
May I ask you to squash your 3 commits into a single one before merging it.

**Comment by Raphcal** [comment]
Done, I squashed everything with `rebase`

**Comment by brasseld** [comment]
Nice 👍

**Pull request merged**
