### PR TITLE
Oauth2-Maper is not support json path search

### PR DESCRIPTION
**Pull request by yang-dw**
fix(oauth2): Oauth2-Maper is not support json path search

Closes gravitee-io/issues#965

### CODE REVIEW

**Comment by cabbage89** [comment]
https://github.com/json-path/JsonPath   
Positioning fields using the json-path expression is more flexible and compatible with the previous configuration

**Comment by brasseld** [comment]
@yang-dw it seems that your PR embeds an old commit for an other issue (https://github.com/gravitee-io/issues/issues/911)

**Comment by cabbage89** [comment]
@brasseld   It does not matter, he has merged from the main repository, this time only two files have been modified, does not contain other changes

**Comment by yang-dw** [comment]
@brasseld  I've created a new PR

**Comment by brasseld** [comment]
I prefer to keep this one.

Can you move the json-path dependency's version into the root pom.xml (the root pom for management-api).

**Comment by yang-dw** [comment]
The old branch has been deleted by me. Can you copy the code and change it in your own way!

**Pull request closed without merging**
