### PR TITLE
X-Forwarded-Host wrong behavior when no port in host name.

### PR DESCRIPTION
**Pull request by k-oliver**
Respect the additional header X-Forwarded-Port to override the port.
If the header X-Forwarded-Host does not contain a port check for protocoll and set it to 443 or 80.

close https://github.com/gravitee-io/issues#3983

@brasseld feel free to change it ;)

### CODE REVIEW

**Comment by brasseld** [comment]
Thanks a lot @k-oliver 

May I ask you to create PR from 1.30.x branch instead of master ?
Master is for 3.x and I think this fix should also be part of latest 1.30.x

Regards,

**Comment by k-oliver** [comment]
@brasseld Sure, i will change the PR.

**Comment by k-oliver** [comment]
Hi @brasseld it seems like my changes are not needed any more. Since 1.30.9 and the latest 1.30.x the code already changed and looks good to me. Do you agree?

**Comment by brasseld** [comment]
Exact, I missed that one!

Thanks for your feedback.

**Pull request closed without merging**
